use sale_management

CREATE TABLE Customer (
  cID   INT AUTO_INCREMENT PRIMARY KEY,
  cName VARCHAR(100) NOT NULL,
  cAge  INT NOT NULL,
  CONSTRAINT chk_customer_age CHECK (cAge BETWEEN 0 AND 120)
);

CREATE TABLE Product (
  pID    INT AUTO_INCREMENT PRIMARY KEY,
  pName  VARCHAR(150) NOT NULL,
  pPrice DECIMAL(12,2) NOT NULL,
  CONSTRAINT chk_product_price CHECK (pPrice >= 0)
);

CREATE TABLE Orders (
  oID          INT AUTO_INCREMENT PRIMARY KEY,
  cID          INT NOT NULL,
  oDate        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  oTotalPrice  DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT fk_orders_customer
    FOREIGN KEY (cID) REFERENCES Customer(cID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT chk_orders_total CHECK (oTotalPrice >= 0)
);

CREATE TABLE IF NOT EXISTS OrderDetail (
  oID   INT NOT NULL,
  pID   INT NOT NULL,
  odQTY INT NOT NULL,
  PRIMARY KEY (oID, pID),

  CONSTRAINT fk_orderdetail_orders
    FOREIGN KEY (oID) REFERENCES Orders(oID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT fk_orderdetail_product
    FOREIGN KEY (pID) REFERENCES Product(pID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT chk_orderdetail_qty CHECK (odQTY > 0)
);





